name: train_logger
description: Train movement GPS logger with live map and CSV export.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.1

  # Location / GPS
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # Geodesic distance
  geodesy: ^0.4.1

  # Local storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # CSV export / share
  share_plus: ^9.0.0
  path_provider: ^2.1.4
  csv: ^6.0.0

  # Misc
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
